# Generated by Django 4.2.3 on 2025-03-13 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a catagorie (e.g. Electronics)', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Write the name of the product')])),
                ('price', models.PositiveIntegerField()),
                ('discription', models.CharField(max_length=600)),
                ('image', models.ImageField(upload_to='')),
                ('Catagorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.catagories')),
            ],
        ),
    ]
